# Generated by Django 6.0.6 on 2026-06-14 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enterprise',
            new_name='Company',
        ),
        migrations.RenameField(
            model_name='target',
            old_name='enterprise',
            new_name='company',
        ),
        migrations.AlterUniqueTogether(
            name='target',
            unique_together={('company', 'user_id')},
        ),
    ]
